export const site = {
    ref: 'KurtLourensPlayground',
    reactId: 'kurt-lourens-desktop',
    url: 'patreonbanner.com',
    captchaKey: '916895db-249a-4ae3-bf39-9fe42e72d196',
    repo: 'https://github1s.com/Khaoz-Topsy/KurtLourens-CV/blob/master/README.md',
    kurt: {
        fullName: 'Kurt Lourens',
        nickName: 'Khaoz-Topsy',
        email: 'hi@kurtlourens.com',
        profilePic: 'https://kurtlourens.com/assets/images/KurtAvatar.svg',
        website: 'https://kurtlourens.com',
        blog: 'https://blog.kurtlourens.com',
        twitter: 'https://twitter.com/KhaozTopsy',
        twitch: 'https://twitch.tv/khaoztopsy',
        github: 'https://github.com/Khaoz-Topsy',
        youtube: 'https://www.youtube.com/channel/UCq31H8M274aWNvLt02_0g7A',
        linkedin: 'https://www.linkedin.com/in/kurtlourensza',
        presentation: 'https://presentation.kurtlourens.com',
        memedeck: 'https://github.com/Khaoz-Topsy/Stream-Meme-Deck',
        googlePlay: 'https://play.google.com/store/apps/details?id=com.kurt_lourens_cv',
        spotifyPublicLikedSongs: 'https://open.spotify.com/embed/playlist/51e9Jvs1ioj0eOeXnHpgUA',
        twitchLivePlayer: 'https://player.twitch.tv/?channel=khaoztopsy&parent=playground.kurtlourens.com&muted=true',
        monitor: 'https://monitor.kurtlourens.com/KhaozNet-AssistantNMS-AssistantApps-RedRubyIT',
        steam: 'https://steamcommunity.com/id/Khaoz-Topsy',
        discord: 'KhaozTopsy#1000',
        khaoznet: {
            homepage: 'https://khaoznet.xyz',
            iot: 'https://iot.khaoznet.xyz',
            plexmedia: 'https://plexmedia.khaoznet.xyz',
            cah: 'https://cah.khaoznet.xyz',
            passport: 'https://passport.khaoznet.xyz',
            zooqle: 'https://zooqle.khaoznet.xyz',
            download: 'https://download.khaoznet.xyz',
            timeline: 'https://timeline.khaoznet.xyz',
            lan: 'https://lan.khaoznet.xyz',
        }
    },
    stream: {
        twitch: 'https://www.twitch.tv/khaoztopsy',
        twitchExtension: 'https://www.twitch.tv/khaoztopsy',
    },
    assistantApps: {
        name: 'AssistantApps',
        api: 'https://api.assistantapps.com',
        email: 'mailto:support@assistantapps.com',
        website: 'https://assistantapps.com',
        docs: 'https://docs.assistantapps.com',
        tools: 'https://tools.assistantapps.com',
        github: 'https://assistantapps.com/github',
        discord: 'https://assistantapps.com/discord',
        discordInviteEmbed: 'https://discord.com/widget?id=625007826913198080&theme=dark',
        patreon: 'https://www.patreon.com/AssistantApps',
        youtube: 'https://www.youtube.com/channel/UCpKNMVk7ZWvBk-psQQZqz5w',
        nms: {
            api: 'https://api.nmsassistant.com',
            website: 'https://nmsassistant.com',
            webapp: 'https://app.nmsassistant.com',
            googlePlay: 'https://play.google.com/store/apps/details?id=com.kurtlourens.no_mans_sky_recipes',
            appleStore: 'https://apps.apple.com/us/app/id1480287625',
            windowsStore: 'https://apps.microsoft.com/store/detail/assistant-for-no-mans-sky/9NQLF7XD0LF3',
            twitter: 'https://twitter.com/AssistantNMS',
            github: 'https://github.com/AssistantNMS',
            nmscd: {
                website: 'https://nmscd.github.io',
                projectsList: 'https://nmscd.github.io/projects.html',
                expeditionAlphabet: 'https://nmscd.github.io/expedition-alphabet',
            }
        },
        sms: {
            api: 'https://api.scrapassistant.com',
            webapp: 'https://scrapassistant.com',
            googlePlay: 'https://play.google.com/store/apps/details?id=com.kurtlourens.scrap_mechanic',
            appleStore: 'https://apps.apple.com/us/app/id1519215611',
            githubOrg: 'https://github.com/AssistantSMS',
            githubApp: 'https://github.com/AssistantSMS/App',
            vscodeUrlForApp: 'https://github1s.com/AssistantSMS/App/blob/master/README.md',
        },
        hyt: {
            api: 'https://api.hytaleassistant.com',
            webapp: 'https://app.hytaleassistant.com',
        },
        patreonBanner: {
            api: 'https://api.assistantapps.stream',
            website: 'https://patreonbanner.com',
            twitch: 'https://dashboard.twitch.tv/extensions/kd1to03pwcm70z85apafwy5rl9mr53-0.1.1',
        }
    },
    tennodex: {
        api: 'https://api.tennodex.com',
        webapp: 'https://tennodex.com',
    }
}