export const site = {
    ref: 'KurtLourensPlayground',
    reactId: 'kurt-lourens-desktop',
    url: 'patreonbanner.com',
    captchaKey: '916895db-249a-4ae3-bf39-9fe42e72d196',
    repo: 'https://github1s.com/Khaoz-Topsy/KurtLourens-CV/blob/master/README.md',
    kurt: {
        fullName: 'Kurt Lourens',
        nickName: 'Khaoz-Topsy',
        profilePic: 'https://kurtlourens.com/assets/images/KurtAvatar.svg',
        website: 'https://kurtlourens.com',
        blog: 'https://blog.kurtlourens.com',
        twitter: 'https://twitter.com/KhaozTopsy',
        twitch: 'https://twitch.tv/khaoztopsy',
        github: 'https://github.com/Khaoz-Topsy',
        youtube: 'https://www.youtube.com/channel/UCq31H8M274aWNvLt02_0g7A',
        linkedin: 'https://www.linkedin.com/in/kurtlourensza/',
        spotifyPublicLikedSongs: 'https://open.spotify.com/embed/playlist/51e9Jvs1ioj0eOeXnHpgUA',
        twitchLivePlayer: 'https://player.twitch.tv/?channel=khaoztopsy&parent=playground.kurtlourens.com&muted=true',
        iotPublication: 'https://culture.entelect.co.za/wp-content/uploads/2021/07/Entelect-Demystifying-IoT-1.pdf',
        twitchPanel: 'https://www.twitch.tv/popout/khaoztopsy/extensions/kd1to03pwcm70z85apafwy5rl9mr53/panel',
        monitor: 'https://monitor.kurtlourens.com/KhaozNet-AssistantNMS-AssistantApps-RedRubyIT',
        steam: 'https://steamcommunity.com/id/Khaoz-Topsy',
        discord: 'KhaozTopsy#1000',
    },
    stream: {
        twitch: 'https://www.twitch.tv/khaoztopsy',
        twitchExtension: 'https://www.twitch.tv/khaoztopsy',
    },
    assistantApps: {
        name: 'AssistantApps',
        email: 'mailto:support@assistantapps.com',
        website: 'https://assistantapps.com',
        tools: 'https://tools.assistantapps.com',
        github: 'https://assistantapps.com/github',
        discord: 'https://assistantapps.com/discord',
        discordInviteEmbed: 'https://discord.com/widget?id=625007826913198080&theme=dark',
        patreon: 'https://www.patreon.com/AssistantApps',
        youtube: 'https://www.youtube.com/channel/UCpKNMVk7ZWvBk-psQQZqz5w',
        nms: {
            website: 'https://nmsassistant.com',
            webapp: 'https://app.nmsassistant.com',
            googlePlay: 'https://play.google.com/store/apps/details?id=com.kurtlourens.no_mans_sky_recipes',
            appleStore: 'https://apps.apple.com/us/app/id1480287625',
            twitter: 'https://twitter.com/AssistantNMS',
            github: 'https://github.com/AssistantNMS',
        },
        sms: {
            webapp: 'https://scrapassistant.com/',
            googlePlay: 'https://play.google.com/store/apps/details?id=com.kurtlourens.scrap_mechanic',
            appleStore: 'https://apps.apple.com/us/app/id1519215611',
            githubOrg: 'https://github.com/AssistantSMS',
            githubApp: 'https://github.com/AssistantSMS/App',
            vscodeUrlForApp: 'https://github1s.com/AssistantSMS/App/blob/master/README.md',
        }
    }
}